In [1]:
import numpy as np
import math

In [2]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [3]:
b = np.array([[1, 3, 3], [4, 5, 6]])
print(b)
print(b.shape)
print(b.dtype)

[[1 3 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
c = np.array([2, 4, 3.3, 5.6])
print(c)
print(c.dtype)

[2.  4.  3.3 5.6]
float64


In [5]:
d = np.zeros((2, 3))
print(d)
e = np.ones((3, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
np.random.rand(2,3) # 0 to 1 (random)

array([[0.59241136, 0.06224082, 0.19907842],
       [0.76460993, 0.3917572 , 0.75031145]])

In [7]:
f = np.arange(10, 30, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28]


In [8]:
np.linspace(2, 15, 5)

array([ 2.  ,  5.25,  8.5 , 11.75, 15.  ])