# Introduction to NumPy Array Creation
NumPy provides powerful tools for numerical computations. Here we learn how to create multi-dimensional arrays, check their properties, and generate arrays filled with zeros, ones, or random numbers.


In [1]:
# Import the numpy library (conventionally as 'np') and the math module
import numpy as np
import math

In [2]:
# Create a 1D NumPy array and check its number of dimensions (ndim)
a = np.array([1, 2, 3])
print(a)
print(a.ndim)

[1 2 3]
1


In [3]:
# Create a 2D array (matrix) and inspect its shape and data type
b = np.array([[1, 3, 3], [4, 5, 6]])
print(b)
print(b.shape)
print(b.dtype)

[[1 3 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
# Create an array of floats and observe numpy's automatic type casting to float64
c = np.array([2, 4, 3.3, 5.6])
print(c)
print(c.dtype)

[2.  4.  3.3 5.6]
float64


In [5]:
# Initialize a 2x3 matrix of zeros and a 3x3 matrix of ones
d = np.zeros((2, 3))
print(d)
e = np.ones((3, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Generate a 2x3 matrix with random values between 0 and 1
np.random.rand(2,3) # 0 to 1 (random)

array([[0.59241136, 0.06224082, 0.19907842],
       [0.76460993, 0.3917572 , 0.75031145]])

In [7]:
# Create an array using arange: from 10 to 29 (exclusive) with a step of 2
f = np.arange(10, 30, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28]


In [8]:
# Create an array of 5 linearly spaced values between 2 and 15
np.linspace(2, 15, 5)

array([ 2.  ,  5.25,  8.5 , 11.75, 15.  ])