# Array Manipulation and Math
This notebook demonstrates basic operations such as element-wise arithmetic, boolean tracking/masking, dot products, reshaping, and aggregate functions (sum, min, max, mean).


In [1]:
# Import the numpy library and the math module
import numpy as np
import math



In [2]:
# Element-wise arithmetic operations on two arrays of the same shape
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a + b
print(c)

c = a - b
print(c)

c = a * b
print(c)

c = a / b
print(c)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [3]:
# Real-world example: convert array of temperatures from Farenheit to Celcius
farenheit = np.array([5, 0, -4, 23, -10])

celcius = (farenheit - 32) * 5/9

print(celcius)

[-15.         -17.77777778 -20.          -5.         -23.33333333]


In [5]:
# Boolean array operations: apply conditional statements to every element
print(celcius > -20)
print(celcius%2 == 0)

[ True  True False  True False]
[False False  True False False]


In [7]:
# Matrix operations: compare element-wise multiplication vs the matrix dot product (@)
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 2], [0, 4]])

print(A*B) # Element-wise Multiplication
print(A@B) # Dot Product

[[ 3  4]
 [ 0 16]]
[[ 3 10]
 [ 9 22]]


In [8]:
# Print the shape of matrix A
print(A.shape)

(2, 2)


In [9]:
# Check data types of integer vs float arrays
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)

arr2 = np.array([10.4, 2.7, 9.3, 6.4])
print(arr2.dtype)

int64
float64


In [10]:
# Demonstrate type coercion or upcasting: adding integer array to float array yields a float array
arr3 = arr1 + arr2
print(arr3)
print(arr3.dtype)

[11.4  4.7 12.3 10.4]
float64


In [12]:
# Utilize aggregate functions to find sum, max, min, and mean
print(arr3.sum())
print(arr3.max())
print(arr3.min())
print(arr3.mean())

38.800000000000004
12.3
4.7
9.700000000000001


In [13]:
# Create an array and immediately reshape it into a 3x5 matrix
b = np.arange(1, 16, 1).reshape(3, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])