In [1]:
import numpy as np
import math



In [2]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a + b
print(c)

c = a - b
print(c)

c = a * b
print(c)

c = a / b
print(c)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [3]:
farenheit = np.array([5, 0, -4, 23, -10])

celcius = (farenheit - 32) * 5/9

print(celcius)

[-15.         -17.77777778 -20.          -5.         -23.33333333]


In [5]:
print(celcius > -20)
print(celcius%2 == 0)

[ True  True False  True False]
[False False  True False False]


In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 2], [0, 4]])

print(A*B) # Element-wise Multiplication
print(A@B) # Dot Product

[[ 3  4]
 [ 0 16]]
[[ 3 10]
 [ 9 22]]


In [8]:
print(A.shape)

(2, 2)


In [9]:
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)

arr2 = np.array([10.4, 2.7, 9.3, 6.4])
print(arr2.dtype)

int64
float64


In [10]:
arr3 = arr1 + arr2
print(arr3)
print(arr3.dtype)

[11.4  4.7 12.3 10.4]
float64


In [12]:
print(arr3.sum())
print(arr3.max())
print(arr3.min())
print(arr3.mean())

38.800000000000004
12.3
4.7
9.700000000000001


In [13]:
b = np.arange(1, 16, 1).reshape(3, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])