In [1]:
import numpy as np

In [3]:
a = np.array([1, 4, 6, 9])
print(a[3])

9


In [ ]:
b = np.array([[1,3,4], [4, 6, 9]])
print(b[1, 2]) # row, column

9


In [6]:
np.array([b[0,1], b[1,1], a[2]])

array([3, 6, 6])

In [8]:
print(b[[0,1,1], [0,2,1]])

[1 9 6]


In [9]:
print(b >5)

[[False False False]
 [False  True  True]]


In [10]:
print(a[a>5])

[6 9]


In [11]:
a = np.array([3,4,2,45,23,65,87])
print(a[2:4])
print(a[2:])
print(a[:4])

[ 2 45]
[ 2 45 23 65 87]
[ 3  4  2 45]


In [14]:
a = np.array([[1,2,34,4], [4,5,6,7], [6,7,8,9]])
print(a)

[[ 1  2 34  4]
 [ 4  5  6  7]
 [ 6  7  8  9]]


In [ ]:
print(a[:2]) # rows
print(a[:2, 1:3]) # rows, columns

[[ 1  2 34  4]
 [ 4  5  6  7]]
[[ 2 34]
 [ 5  6]]


In [15]:
sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50
